//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceGapslabs")]
public interface ServiceGapslabs {
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetOSMmeshFromOsmId", ReplyAction="http://tempuri.org/ServiceGapslabs/GetOSMmeshFromOsmIdResponse")]
    GaPSLabs.Geometry.GameObject GetOSMmeshFromOsmId(string OSMid, GaPSLabs.Geometry.Vector3 MinPointOnMap, GapslabWCFservice.BoundsWCF bounds, GaPSLabs.Geometry.MapProperties properties, string connPostGreSql, string OSMObjectType, bool RemoveRedundantPointsOnTheSameLine, float RedundantPointErrorThreshold, bool SegmentLines);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetRelationIds", ReplyAction="http://tempuri.org/ServiceGapslabs/GetRelationIdsResponse")]
    string[] GetRelationIds(string connectionString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetRelationsContainingMembers", ReplyAction="http://tempuri.org/ServiceGapslabs/GetRelationsContainingMembersResponse")]
    string[] GetRelationsContainingMembers(string connectionString, string[] memberIds, int memberType, string memberRole);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetRelationMembers", ReplyAction="http://tempuri.org/ServiceGapslabs/GetRelationMembersResponse")]
    GapslabWCFservice.MemberWCF[] GetRelationMembers(string connectionString, string relationId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetWayIds", ReplyAction="http://tempuri.org/ServiceGapslabs/GetWayIdsResponse")]
    string[] GetWayIds(string connectionString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetWayIdsWithIdCriteria", ReplyAction="http://tempuri.org/ServiceGapslabs/GetWayIdsWithIdCriteriaResponse")]
    string[] GetWayIdsWithIdCriteria(string connectionString, string IdCriteria);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetWayIdsInStockholm", ReplyAction="http://tempuri.org/ServiceGapslabs/GetWayIdsInStockholmResponse")]
    string[] GetWayIdsInStockholm(string connectionString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetWayIdsInBound", ReplyAction="http://tempuri.org/ServiceGapslabs/GetWayIdsInBoundResponse")]
    string[] GetWayIdsInBound(string connectionString, GapslabWCFservice.BoundsWCF bound);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetRelationBuildingsInBound", ReplyAction="http://tempuri.org/ServiceGapslabs/GetRelationBuildingsInBoundResponse")]
    string[] GetRelationBuildingsInBound(string connectionString, GapslabWCFservice.BoundsWCF bound);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetWayIdsWithTags", ReplyAction="http://tempuri.org/ServiceGapslabs/GetWayIdsWithTagsResponse")]
    string[] GetWayIdsWithTags(string connectionString, GapslabWCFservice.BoundsWCF bound, string[][] tags);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetWayExtIdsInBound", ReplyAction="http://tempuri.org/ServiceGapslabs/GetWayExtIdsInBoundResponse")]
    string[][] GetWayExtIdsInBound(string connectionString, GapslabWCFservice.BoundsWCF bound);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetNodeIdsInBoundWithInfo", ReplyAction="http://tempuri.org/ServiceGapslabs/GetNodeIdsInBoundWithInfoResponse")]
    string[] GetNodeIdsInBoundWithInfo(string connectionString, GapslabWCFservice.BoundsWCF bound, string infoTag);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetNodeIdsInBoundWithKeyValueTag", ReplyAction="http://tempuri.org/ServiceGapslabs/GetNodeIdsInBoundWithKeyValueTagResponse")]
    string[] GetNodeIdsInBoundWithKeyValueTag(string connectionString, GapslabWCFservice.BoundsWCF bound, string[][] infoTag);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetNodeInfo", ReplyAction="http://tempuri.org/ServiceGapslabs/GetNodeInfoResponse")]
    GapslabWCFservice.OsmNodeWCF GetNodeInfo(string nodeid, string connectionString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetWayExtNodes", ReplyAction="http://tempuri.org/ServiceGapslabs/GetWayExtNodesResponse")]
    GapslabWCFservice.OsmNodeWCF[] GetWayExtNodes(string wayid, string connectionString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetWayNodes", ReplyAction="http://tempuri.org/ServiceGapslabs/GetWayNodesResponse")]
    GapslabWCFservice.OsmNodeWCF[] GetWayNodes(string wayid, string connectionString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetRelationTags", ReplyAction="http://tempuri.org/ServiceGapslabs/GetRelationTagsResponse")]
    GapslabWCFservice.TagWCF[] GetRelationTags(string relationid, string connectionString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetWayTags", ReplyAction="http://tempuri.org/ServiceGapslabs/GetWayTagsResponse")]
    GapslabWCFservice.TagWCF[] GetWayTags(string wayid, string connectionString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetWayTagsStockholm", ReplyAction="http://tempuri.org/ServiceGapslabs/GetWayTagsStockholmResponse")]
    GapslabWCFservice.TagWCF[] GetWayTagsStockholm(string wayid, string connectionString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetNodeTags", ReplyAction="http://tempuri.org/ServiceGapslabs/GetNodeTagsResponse")]
    GapslabWCFservice.TagWCF[] GetNodeTags(string nodeid, string connectionString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetBounds", ReplyAction="http://tempuri.org/ServiceGapslabs/GetBoundsResponse")]
    GapslabWCFservice.BoundsWCF GetBounds(string connectionString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetRoutePath", ReplyAction="http://tempuri.org/ServiceGapslabs/GetRoutePathResponse")]
    GapslabWCFservice.OsmNodeWCF[] GetRoutePath(string routeId, int memberType, string connectionString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetRoutePathCustom", ReplyAction="http://tempuri.org/ServiceGapslabs/GetRoutePathCustomResponse")]
    GapslabWCFservice.OsmNodeWCF[] GetRoutePathCustom(string routeId, int memberType, string connectionString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/InitializeRouter", ReplyAction="http://tempuri.org/ServiceGapslabs/InitializeRouterResponse")]
    string InitializeRouter(string connectionString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/ResolvePoint", ReplyAction="http://tempuri.org/ServiceGapslabs/ResolvePointResponse")]
    GapslabWCFservice.OsmNodeWCF ResolvePoint(OsmSharp.Routing.VehicleEnum vehicle, GapslabWCFservice.OsmNodeWCF currentNode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/RouteUsingDykstra", ReplyAction="http://tempuri.org/ServiceGapslabs/RouteUsingDykstraResponse")]
    GapslabWCFservice.OsmNodeWCF[] RouteUsingDykstra(OsmSharp.Routing.VehicleEnum vehicle, GapslabWCFservice.OsmNodeWCF pointA, GapslabWCFservice.OsmNodeWCF pointB);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetGeometryCollectionSingleObject", ReplyAction="http://tempuri.org/ServiceGapslabs/GetGeometryCollectionSingleObjectResponse")]
    Aram.OSMParser.geometryCollection GetGeometryCollectionSingleObject(string id, bool includeLargeObject, string connectionString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetGeometryCollection", ReplyAction="http://tempuri.org/ServiceGapslabs/GetGeometryCollectionResponse")]
    Aram.OSMParser.geometryCollection[] GetGeometryCollection(bool includeLargeObject, string SearchCriteriaWhereClause, string connectionString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetGeometryCollectionMinimal", ReplyAction="http://tempuri.org/ServiceGapslabs/GetGeometryCollectionMinimalResponse")]
    long[] GetGeometryCollectionMinimal(string SearchCriteriaWhereClause, string connectionString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/InitializeSimulationList", ReplyAction="http://tempuri.org/ServiceGapslabs/InitializeSimulationListResponse")]
    void InitializeSimulationList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/DisposeSimulation", ReplyAction="http://tempuri.org/ServiceGapslabs/DisposeSimulationResponse")]
    bool DisposeSimulation(string SimulationID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GenerateRandomID", ReplyAction="http://tempuri.org/ServiceGapslabs/GenerateRandomIDResponse")]
    string GenerateRandomID(string initial);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetTotalTimesteps", ReplyAction="http://tempuri.org/ServiceGapslabs/GetTotalTimestepsResponse")]
    int GetTotalTimesteps();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetTotalTimestepsList", ReplyAction="http://tempuri.org/ServiceGapslabs/GetTotalTimestepsListResponse")]
    int GetTotalTimestepsList(int SimulationID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetTimestepAt", ReplyAction="http://tempuri.org/ServiceGapslabs/GetTimestepAtResponse")]
    GapslabWCFservice.TimeStep GetTimestepAt(int index);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetTimestepAtList", ReplyAction="http://tempuri.org/ServiceGapslabs/GetTimestepAtListResponse")]
    GapslabWCFservice.TimeStep GetTimestepAtList(int index, int SimulationID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetSimpleTimestepAtList", ReplyAction="http://tempuri.org/ServiceGapslabs/GetSimpleTimestepAtListResponse")]
    GapslabWCFservice.SimpleTimeStep GetSimpleTimestepAtList(int index, int SimulationID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetSimulationName", ReplyAction="http://tempuri.org/ServiceGapslabs/GetSimulationNameResponse")]
    string GetSimulationName();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetSimulationNameList", ReplyAction="http://tempuri.org/ServiceGapslabs/GetSimulationNameListResponse")]
    string GetSimulationNameList(int SimulationID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetSimulationDescription", ReplyAction="http://tempuri.org/ServiceGapslabs/GetSimulationDescriptionResponse")]
    string GetSimulationDescription();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/GetSimulationDescriptionList", ReplyAction="http://tempuri.org/ServiceGapslabs/GetSimulationDescriptionListResponse")]
    string GetSimulationDescriptionList(int SimulationID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/IsSimulationLoaded", ReplyAction="http://tempuri.org/ServiceGapslabs/IsSimulationLoadedResponse")]
    bool IsSimulationLoaded();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/IsSimulationLoadedList", ReplyAction="http://tempuri.org/ServiceGapslabs/IsSimulationLoadedListResponse")]
    bool IsSimulationLoadedList(int SimulationID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/LoadSUMOFCDSimulation", ReplyAction="http://tempuri.org/ServiceGapslabs/LoadSUMOFCDSimulationResponse")]
    void LoadSUMOFCDSimulation(string filename);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGapslabs/LoadSUMOFCDSimulationList", ReplyAction="http://tempuri.org/ServiceGapslabs/LoadSUMOFCDSimulationListResponse")]
    int LoadSUMOFCDSimulationList(string filename, string ObjectIDPostfix);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ServiceGapslabsChannel : ServiceGapslabs, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceGapslabsClient : System.ServiceModel.ClientBase<ServiceGapslabs>, ServiceGapslabs {
    
    public ServiceGapslabsClient() {
    }
    
    public ServiceGapslabsClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public ServiceGapslabsClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public ServiceGapslabsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public ServiceGapslabsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress) {
    }
    
    public GaPSLabs.Geometry.GameObject GetOSMmeshFromOsmId(string OSMid, GaPSLabs.Geometry.Vector3 MinPointOnMap, GapslabWCFservice.BoundsWCF bounds, GaPSLabs.Geometry.MapProperties properties, string connPostGreSql, string OSMObjectType, bool RemoveRedundantPointsOnTheSameLine, float RedundantPointErrorThreshold, bool SegmentLines) {
        return base.Channel.GetOSMmeshFromOsmId(OSMid, MinPointOnMap, bounds, properties, connPostGreSql, OSMObjectType, RemoveRedundantPointsOnTheSameLine, RedundantPointErrorThreshold, SegmentLines);
    }
    
    public string[] GetRelationIds(string connectionString) {
        return base.Channel.GetRelationIds(connectionString);
    }
    
    public string[] GetRelationsContainingMembers(string connectionString, string[] memberIds, int memberType, string memberRole) {
        return base.Channel.GetRelationsContainingMembers(connectionString, memberIds, memberType, memberRole);
    }
    
    public GapslabWCFservice.MemberWCF[] GetRelationMembers(string connectionString, string relationId) {
        return base.Channel.GetRelationMembers(connectionString, relationId);
    }
    
    public string[] GetWayIds(string connectionString) {
        return base.Channel.GetWayIds(connectionString);
    }
    
    public string[] GetWayIdsWithIdCriteria(string connectionString, string IdCriteria) {
        return base.Channel.GetWayIdsWithIdCriteria(connectionString, IdCriteria);
    }
    
    public string[] GetWayIdsInStockholm(string connectionString) {
        return base.Channel.GetWayIdsInStockholm(connectionString);
    }
    
    public string[] GetWayIdsInBound(string connectionString, GapslabWCFservice.BoundsWCF bound) {
        return base.Channel.GetWayIdsInBound(connectionString, bound);
    }
    
    public string[] GetRelationBuildingsInBound(string connectionString, GapslabWCFservice.BoundsWCF bound) {
        return base.Channel.GetRelationBuildingsInBound(connectionString, bound);
    }
    
    public string[] GetWayIdsWithTags(string connectionString, GapslabWCFservice.BoundsWCF bound, string[][] tags) {
        return base.Channel.GetWayIdsWithTags(connectionString, bound, tags);
    }
    
    public string[][] GetWayExtIdsInBound(string connectionString, GapslabWCFservice.BoundsWCF bound) {
        return base.Channel.GetWayExtIdsInBound(connectionString, bound);
    }
    
    public string[] GetNodeIdsInBoundWithInfo(string connectionString, GapslabWCFservice.BoundsWCF bound, string infoTag) {
        return base.Channel.GetNodeIdsInBoundWithInfo(connectionString, bound, infoTag);
    }
    
    public string[] GetNodeIdsInBoundWithKeyValueTag(string connectionString, GapslabWCFservice.BoundsWCF bound, string[][] infoTag) {
        return base.Channel.GetNodeIdsInBoundWithKeyValueTag(connectionString, bound, infoTag);
    }
    
    public GapslabWCFservice.OsmNodeWCF GetNodeInfo(string nodeid, string connectionString) {
        return base.Channel.GetNodeInfo(nodeid, connectionString);
    }
    
    public GapslabWCFservice.OsmNodeWCF[] GetWayExtNodes(string wayid, string connectionString) {
        return base.Channel.GetWayExtNodes(wayid, connectionString);
    }
    
    public GapslabWCFservice.OsmNodeWCF[] GetWayNodes(string wayid, string connectionString) {
        return base.Channel.GetWayNodes(wayid, connectionString);
    }
    
    public GapslabWCFservice.TagWCF[] GetRelationTags(string relationid, string connectionString) {
        return base.Channel.GetRelationTags(relationid, connectionString);
    }
    
    public GapslabWCFservice.TagWCF[] GetWayTags(string wayid, string connectionString) {
        return base.Channel.GetWayTags(wayid, connectionString);
    }
    
    public GapslabWCFservice.TagWCF[] GetWayTagsStockholm(string wayid, string connectionString) {
        return base.Channel.GetWayTagsStockholm(wayid, connectionString);
    }
    
    public GapslabWCFservice.TagWCF[] GetNodeTags(string nodeid, string connectionString) {
        return base.Channel.GetNodeTags(nodeid, connectionString);
    }
    
    public GapslabWCFservice.BoundsWCF GetBounds(string connectionString) {
        return base.Channel.GetBounds(connectionString);
    }
    
    public GapslabWCFservice.OsmNodeWCF[] GetRoutePath(string routeId, int memberType, string connectionString) {
        return base.Channel.GetRoutePath(routeId, memberType, connectionString);
    }
    
    public GapslabWCFservice.OsmNodeWCF[] GetRoutePathCustom(string routeId, int memberType, string connectionString) {
        return base.Channel.GetRoutePathCustom(routeId, memberType, connectionString);
    }
    
    public string InitializeRouter(string connectionString) {
        return base.Channel.InitializeRouter(connectionString);
    }
    
    public GapslabWCFservice.OsmNodeWCF ResolvePoint(OsmSharp.Routing.VehicleEnum vehicle, GapslabWCFservice.OsmNodeWCF currentNode) {
        return base.Channel.ResolvePoint(vehicle, currentNode);
    }
    
    public GapslabWCFservice.OsmNodeWCF[] RouteUsingDykstra(OsmSharp.Routing.VehicleEnum vehicle, GapslabWCFservice.OsmNodeWCF pointA, GapslabWCFservice.OsmNodeWCF pointB) {
        return base.Channel.RouteUsingDykstra(vehicle, pointA, pointB);
    }
    
    public Aram.OSMParser.geometryCollection GetGeometryCollectionSingleObject(string id, bool includeLargeObject, string connectionString) {
        return base.Channel.GetGeometryCollectionSingleObject(id, includeLargeObject, connectionString);
    }
    
    public Aram.OSMParser.geometryCollection[] GetGeometryCollection(bool includeLargeObject, string SearchCriteriaWhereClause, string connectionString) {
        return base.Channel.GetGeometryCollection(includeLargeObject, SearchCriteriaWhereClause, connectionString);
    }
    
    public long[] GetGeometryCollectionMinimal(string SearchCriteriaWhereClause, string connectionString) {
        return base.Channel.GetGeometryCollectionMinimal(SearchCriteriaWhereClause, connectionString);
    }
    
    public void InitializeSimulationList() {
        base.Channel.InitializeSimulationList();
    }
    
    public bool DisposeSimulation(string SimulationID) {
        return base.Channel.DisposeSimulation(SimulationID);
    }
    
    public string GenerateRandomID(string initial) {
        return base.Channel.GenerateRandomID(initial);
    }
    
    public int GetTotalTimesteps() {
        return base.Channel.GetTotalTimesteps();
    }
    
    public int GetTotalTimestepsList(int SimulationID) {
        return base.Channel.GetTotalTimestepsList(SimulationID);
    }
    
    public GapslabWCFservice.TimeStep GetTimestepAt(int index) {
        return base.Channel.GetTimestepAt(index);
    }
    
    public GapslabWCFservice.TimeStep GetTimestepAtList(int index, int SimulationID) {
        return base.Channel.GetTimestepAtList(index, SimulationID);
    }
    
    public GapslabWCFservice.SimpleTimeStep GetSimpleTimestepAtList(int index, int SimulationID) {
        return base.Channel.GetSimpleTimestepAtList(index, SimulationID);
    }
    
    public string GetSimulationName() {
        return base.Channel.GetSimulationName();
    }
    
    public string GetSimulationNameList(int SimulationID) {
        return base.Channel.GetSimulationNameList(SimulationID);
    }
    
    public string GetSimulationDescription() {
        return base.Channel.GetSimulationDescription();
    }
    
    public string GetSimulationDescriptionList(int SimulationID) {
        return base.Channel.GetSimulationDescriptionList(SimulationID);
    }
    
    public bool IsSimulationLoaded() {
        return base.Channel.IsSimulationLoaded();
    }
    
    public bool IsSimulationLoadedList(int SimulationID) {
        return base.Channel.IsSimulationLoadedList(SimulationID);
    }
    
    public void LoadSUMOFCDSimulation(string filename) {
        base.Channel.LoadSUMOFCDSimulation(filename);
    }
    
    public int LoadSUMOFCDSimulationList(string filename, string ObjectIDPostfix) {
        return base.Channel.LoadSUMOFCDSimulationList(filename, ObjectIDPostfix);
    }
}
namespace GaPSLabs.Geometry {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vector3", Namespace="http://schemas.datacontract.org/2004/07/GaPSLabs.Geometry")]
    public partial class Vector3 : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float xField;
        
        private float yField;
        
        private float zField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MapProperties", Namespace="http://schemas.datacontract.org/2004/07/GaPSLabs.Geometry")]
    public partial class MapProperties : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GaPSLabs.Geometry.Material AreaMaterialField;
        
        private GaPSLabs.Geometry.Color BuildingColorField;
        
        private float BuildingHeightField;
        
        private GaPSLabs.Geometry.DiscreetCurve BuildingHeightVariationField;
        
        private float BuildingLineThicknessField;
        
        private GaPSLabs.Geometry.Material BuildingMaterialField;
        
        private GaPSLabs.Geometry.Vector2 CombinationOptimizationSizeField;
        
        private GaPSLabs.Geometry.Material CycleWayMaterialField;
        
        private float CyclewayWidthField;
        
        private GaPSLabs.Geometry.Material FootWayMaterialField;
        
        private float FootwayWidthField;
        
        private GaPSLabs.Geometry.Color LineColorEndField;
        
        private GaPSLabs.Geometry.Color LineColorStartField;
        
        private GaPSLabs.Geometry.Vector3 MinPointOnMapField;
        
        private string NameField;
        
        private bool OverrideDatabaseConnectionField;
        
        private string OverridenConnectionStringField;
        
        private GaPSLabs.Geometry.Material RailWayMaterialField;
        
        private GaPSLabs.Geometry.Material ResidentialMaterialField;
        
        private float RoadLineThicknessField;
        
        private GaPSLabs.Geometry.Material RoadMaterialField;
        
        private float RoadWidthField;
        
        private GaPSLabs.Geometry.Vector2 ScaleField;
        
        private GaPSLabs.Geometry.Material ServiceMaterialField;
        
        private GaPSLabs.Geometry.Material StepsMaterialField;
        
        private GaPSLabs.Geometry.Material WaterMaterialField;
        
        private string filenameField;
        
        private double maxLatField;
        
        private double maxLonField;
        
        private double minLatField;
        
        private double minLonField;
        
        private float[] minMaxXField;
        
        private float[] minMaxYField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Material AreaMaterial {
            get {
                return this.AreaMaterialField;
            }
            set {
                this.AreaMaterialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Color BuildingColor {
            get {
                return this.BuildingColorField;
            }
            set {
                this.BuildingColorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float BuildingHeight {
            get {
                return this.BuildingHeightField;
            }
            set {
                this.BuildingHeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.DiscreetCurve BuildingHeightVariation {
            get {
                return this.BuildingHeightVariationField;
            }
            set {
                this.BuildingHeightVariationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float BuildingLineThickness {
            get {
                return this.BuildingLineThicknessField;
            }
            set {
                this.BuildingLineThicknessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Material BuildingMaterial {
            get {
                return this.BuildingMaterialField;
            }
            set {
                this.BuildingMaterialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Vector2 CombinationOptimizationSize {
            get {
                return this.CombinationOptimizationSizeField;
            }
            set {
                this.CombinationOptimizationSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Material CycleWayMaterial {
            get {
                return this.CycleWayMaterialField;
            }
            set {
                this.CycleWayMaterialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float CyclewayWidth {
            get {
                return this.CyclewayWidthField;
            }
            set {
                this.CyclewayWidthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Material FootWayMaterial {
            get {
                return this.FootWayMaterialField;
            }
            set {
                this.FootWayMaterialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FootwayWidth {
            get {
                return this.FootwayWidthField;
            }
            set {
                this.FootwayWidthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Color LineColorEnd {
            get {
                return this.LineColorEndField;
            }
            set {
                this.LineColorEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Color LineColorStart {
            get {
                return this.LineColorStartField;
            }
            set {
                this.LineColorStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Vector3 MinPointOnMap {
            get {
                return this.MinPointOnMapField;
            }
            set {
                this.MinPointOnMapField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OverrideDatabaseConnection {
            get {
                return this.OverrideDatabaseConnectionField;
            }
            set {
                this.OverrideDatabaseConnectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OverridenConnectionString {
            get {
                return this.OverridenConnectionStringField;
            }
            set {
                this.OverridenConnectionStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Material RailWayMaterial {
            get {
                return this.RailWayMaterialField;
            }
            set {
                this.RailWayMaterialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Material ResidentialMaterial {
            get {
                return this.ResidentialMaterialField;
            }
            set {
                this.ResidentialMaterialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float RoadLineThickness {
            get {
                return this.RoadLineThicknessField;
            }
            set {
                this.RoadLineThicknessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Material RoadMaterial {
            get {
                return this.RoadMaterialField;
            }
            set {
                this.RoadMaterialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float RoadWidth {
            get {
                return this.RoadWidthField;
            }
            set {
                this.RoadWidthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Vector2 Scale {
            get {
                return this.ScaleField;
            }
            set {
                this.ScaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Material ServiceMaterial {
            get {
                return this.ServiceMaterialField;
            }
            set {
                this.ServiceMaterialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Material StepsMaterial {
            get {
                return this.StepsMaterialField;
            }
            set {
                this.StepsMaterialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Material WaterMaterial {
            get {
                return this.WaterMaterialField;
            }
            set {
                this.WaterMaterialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double maxLat {
            get {
                return this.maxLatField;
            }
            set {
                this.maxLatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double maxLon {
            get {
                return this.maxLonField;
            }
            set {
                this.maxLonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double minLat {
            get {
                return this.minLatField;
            }
            set {
                this.minLatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double minLon {
            get {
                return this.minLonField;
            }
            set {
                this.minLonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float[] minMaxX {
            get {
                return this.minMaxXField;
            }
            set {
                this.minMaxXField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float[] minMaxY {
            get {
                return this.minMaxYField;
            }
            set {
                this.minMaxYField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Material", Namespace="http://schemas.datacontract.org/2004/07/GaPSLabs.Geometry")]
    public partial class Material : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Color", Namespace="http://schemas.datacontract.org/2004/07/GaPSLabs.Geometry")]
    public partial class Color : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BField;
        
        private int GField;
        
        private int RField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int B {
            get {
                return this.BField;
            }
            set {
                this.BField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int G {
            get {
                return this.GField;
            }
            set {
                this.GField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int R {
            get {
                return this.RField;
            }
            set {
                this.RField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiscreetCurve", Namespace="http://schemas.datacontract.org/2004/07/GaPSLabs.Geometry")]
    public partial class DiscreetCurve : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CurrentField;
        
        private float[] dataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Current {
            get {
                return this.CurrentField;
            }
            set {
                this.CurrentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vector2", Namespace="http://schemas.datacontract.org/2004/07/GaPSLabs.Geometry")]
    public partial class Vector2 : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float xField;
        
        private float yField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameObject", Namespace="http://schemas.datacontract.org/2004/07/GaPSLabs.Geometry")]
    public partial class GameObject : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        private GaPSLabs.Geometry.Material materialField;
        
        private GaPSLabs.Geometry.Mesh meshField;
        
        private GaPSLabs.Geometry.Vector3 positionField;
        
        private string tagField;
        
        private GaPSLabs.Geometry.GameObject.OSMType typeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Material material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Mesh mesh {
            get {
                return this.meshField;
            }
            set {
                this.meshField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Vector3 position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.GameObject.OSMType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="GameObject.OSMType", Namespace="http://schemas.datacontract.org/2004/07/GaPSLabs.Geometry")]
        public enum OSMType : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Node = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Line = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Polygon = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Relation = 3,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mesh", Namespace="http://schemas.datacontract.org/2004/07/GaPSLabs.Geometry")]
    public partial class Mesh : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GaPSLabs.Geometry.Vector3[] normalsField;
        
        private GaPSLabs.Geometry.Vector4[] tangentsField;
        
        private int[] trianglesField;
        
        private GaPSLabs.Geometry.Vector2[] uvField;
        
        private GaPSLabs.Geometry.Vector3[] verticesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Vector3[] normals {
            get {
                return this.normalsField;
            }
            set {
                this.normalsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Vector4[] tangents {
            get {
                return this.tangentsField;
            }
            set {
                this.tangentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] triangles {
            get {
                return this.trianglesField;
            }
            set {
                this.trianglesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Vector2[] uv {
            get {
                return this.uvField;
            }
            set {
                this.uvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GaPSLabs.Geometry.Vector3[] vertices {
            get {
                return this.verticesField;
            }
            set {
                this.verticesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vector4", Namespace="http://schemas.datacontract.org/2004/07/GaPSLabs.Geometry")]
    public partial class Vector4 : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float wField;
        
        private float xField;
        
        private float yField;
        
        private float zField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float w {
            get {
                return this.wField;
            }
            set {
                this.wField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
    }
}
namespace GapslabWCFservice {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoundsWCF", Namespace="http://schemas.datacontract.org/2004/07/GapslabWCFservice")]
    public partial class BoundsWCF : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double maxlatField;
        
        private double maxlonField;
        
        private double minlatField;
        
        private double minlonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double maxlat {
            get {
                return this.maxlatField;
            }
            set {
                this.maxlatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double maxlon {
            get {
                return this.maxlonField;
            }
            set {
                this.maxlonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double minlat {
            get {
                return this.minlatField;
            }
            set {
                this.minlatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double minlon {
            get {
                return this.minlonField;
            }
            set {
                this.minlonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberWCF", Namespace="http://schemas.datacontract.org/2004/07/GapslabWCFservice")]
    public partial class MemberWCF : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ReferenceIdField;
        
        private string RelationIdField;
        
        private string RoleField;
        
        private int TypeField;
        
        private int orderField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceId {
            get {
                return this.ReferenceIdField;
            }
            set {
                this.ReferenceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelationId {
            get {
                return this.RelationIdField;
            }
            set {
                this.RelationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                this.RoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OsmNodeWCF", Namespace="http://schemas.datacontract.org/2004/07/GapslabWCFservice")]
    public partial class OsmNodeWCF : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string idField;
        
        private double latField;
        
        private double lonField;
        
        private int orderField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lon {
            get {
                return this.lonField;
            }
            set {
                this.lonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TagWCF", Namespace="http://schemas.datacontract.org/2004/07/GapslabWCFservice")]
    public partial class TagWCF : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string[] KeyValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] KeyValue {
            get {
                return this.KeyValueField;
            }
            set {
                this.KeyValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeStep", Namespace="http://schemas.datacontract.org/2004/07/GapslabWCFservice")]
    public partial class TimeStep : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GapslabWCFservice.VehicleFCD[] VehiclesField;
        
        private System.DateTime iMobilityTimeField;
        
        private int indexField;
        
        private float timeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GapslabWCFservice.VehicleFCD[] Vehicles {
            get {
                return this.VehiclesField;
            }
            set {
                this.VehiclesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime iMobilityTime {
            get {
                return this.iMobilityTimeField;
            }
            set {
                this.iMobilityTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleFCD", Namespace="http://schemas.datacontract.org/2004/07/GapslabWCFservice")]
    public partial class VehicleFCD : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float AngleField;
        
        private string IdField;
        
        private string LaneField;
        
        private float LatitudeField;
        
        private float LongitudeField;
        
        private float PosField;
        
        private float SlopeField;
        
        private float SpeedField;
        
        private GapslabWCFservice.SUMOSimulationFCDVehicleType VehicleTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Angle {
            get {
                return this.AngleField;
            }
            set {
                this.AngleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lane {
            get {
                return this.LaneField;
            }
            set {
                this.LaneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Pos {
            get {
                return this.PosField;
            }
            set {
                this.PosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Slope {
            get {
                return this.SlopeField;
            }
            set {
                this.SlopeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Speed {
            get {
                return this.SpeedField;
            }
            set {
                this.SpeedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GapslabWCFservice.SUMOSimulationFCDVehicleType VehicleType {
            get {
                return this.VehicleTypeField;
            }
            set {
                this.VehicleTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SUMOSimulationFCD.VehicleType", Namespace="http://schemas.datacontract.org/2004/07/GapslabWCFservice")]
    public enum SUMOSimulationFCDVehicleType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Simple = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimpleTimeStep", Namespace="http://schemas.datacontract.org/2004/07/GapslabWCFservice")]
    public partial class SimpleTimeStep : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string[] VehicleIdsField;
        
        private float[] VehicleLatsField;
        
        private float[] VehicleLongsField;
        
        private System.DateTime iMobilityTimeField;
        
        private int indexField;
        
        private float timeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] VehicleIds {
            get {
                return this.VehicleIdsField;
            }
            set {
                this.VehicleIdsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float[] VehicleLats {
            get {
                return this.VehicleLatsField;
            }
            set {
                this.VehicleLatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float[] VehicleLongs {
            get {
                return this.VehicleLongsField;
            }
            set {
                this.VehicleLongsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime iMobilityTime {
            get {
                return this.iMobilityTimeField;
            }
            set {
                this.iMobilityTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
    }
}
namespace OsmSharp.Routing {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleEnum", Namespace="http://schemas.datacontract.org/2004/07/OsmSharp.Routing")]
    public enum VehicleEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pedestrian = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bicycle = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Moped = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MotorCycle = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Car = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmallTruck = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BigTruck = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bus = 7,
    }
}
namespace Aram.OSMParser {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="geometryCollection", Namespace="http://schemas.datacontract.org/2004/07/Aram.OSMParser")]
    public partial class geometryCollection : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string formatField;
        
        private int gisIdField;
        
        private string gisTypeField;
        
        private long idField;
        
        private byte[] largeObjectField;
        
        private System.DateTime lastUpdateField;
        
        private int latitudeField;
        
        private int longitudeField;
        
        private string nameField;
        
        private Aram.OSMParser.Vector3GaPS pivotField;
        
        private Aram.OSMParser.GaPSlabsVersion versionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int gisId {
            get {
                return this.gisIdField;
            }
            set {
                this.gisIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gisType {
            get {
                return this.gisTypeField;
            }
            set {
                this.gisTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] largeObject {
            get {
                return this.largeObjectField;
            }
            set {
                this.largeObjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime lastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Aram.OSMParser.Vector3GaPS pivot {
            get {
                return this.pivotField;
            }
            set {
                this.pivotField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Aram.OSMParser.GaPSlabsVersion version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vector3GaPS", Namespace="http://schemas.datacontract.org/2004/07/Aram.OSMParser")]
    public partial class Vector3GaPS : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float xField;
        
        private float yField;
        
        private float zField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GaPSlabsVersion", Namespace="http://schemas.datacontract.org/2004/07/Aram.OSMParser")]
    public partial class GaPSlabsVersion : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int majorField;
        
        private int minorField;
        
        private string versionTitleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int major {
            get {
                return this.majorField;
            }
            set {
                this.majorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int minor {
            get {
                return this.minorField;
            }
            set {
                this.minorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string versionTitle {
            get {
                return this.versionTitleField;
            }
            set {
                this.versionTitleField = value;
            }
        }
    }
}

